### ISSUE TITLE
build tab not found in repository UI

### ISSUE THREAD

**Issue by dayeguilaiye** [quay/mirror-registry#123]
I have installed quay by mirror-registry.
I found that there is build tag in quay: https://docs.quay.io/guides/building.html

But the tag not exist in my quay.

Does anyone know why?

**Comment by dmesser** [comment]
Hi @dayeguilaiye - I assume you are referring to the minimal distribution of Quay known as "[mirror registry for OpenShift](https://docs.openshift.com/container-platform/4.12/installing/disconnected_install/installing-mirroring-creating-registry.html)" and the **tab** in the UI for _Builds_? 

If so, the mirror registry does not support that use case and the builder feature has been disabled. As implied by the name, this small distribution of Quay is aimed at a content mirror. It does not have all the features of Quay enabled. For that you will have to deploy the Quay as described here: https://docs.projectquay.io/deploy_quay.html

**Comment by dayeguilaiye** [comment]
@dmesser  Thanks for your reply, that really helps a lot !
