### ISSUE TITLE
Absence of `quayHostname` or `targetHostname` should default to local hostname

### ISSUE THREAD

**Issue by dmesser** [quay/mirror-registry#44]
When running `mirror-registry` without either the `--quayHostname` or `--targetHostname` parameter, it currently defaults to `localhost`. This is not useful for a registry that is supposed to be used by external clients for pulling images. 

Instead the default should be to fallback to the output of `hostname -f`.

**Comment by HammerMeetNail** [comment]
Created https://issues.redhat.com/browse/PROJQUAY-3079 to track.
