### ISSUE TITLE
Make sure that `quay-pod` is properly instantiated

### ISSUE THREAD

**Issue by pbertera** [quay/mirror-registry#48]
The pod `quay-pod` is created during the installation of `mirror-registry`. If for some reasons gets removed quay fails to start.
The systemd units should depends on another unit that makes sure that the pod is properly created

**Comment by HammerMeetNail** [comment]
@pbertera Thanks for raising, we've created https://issues.redhat.com/browse/PROJQUAY-3261 to track the work.
