### ISSUE TITLE
Problem when etckeeper is installed

### ISSUE THREAD

**Issue by rabin-io** [quay/mirror-registry#62]
Seems like when `etckeeper` is installed, this can cause a problem if the `/etc/quay-install` path is not added to `/etc/.gitignore` file. And when triggered by dnf/yum (pre/post hooks) the git process will try to add the content of `/etc/quay-install` and hang.

the installer should check if the etckeeper is installed and add the above path to the .gitignore file.

```sh
echo 'quay-install/' >> /etc/.gitignore
```

**Comment by HammerMeetNail** [comment]
I wonder if we should change the default install location to be something like `/var/quay-install` instead of `/etc/quay-install`. If I'm not mistaken I think we store a lot more than just configuration files there. @jonathankingfc What do you think?

**Comment by rabin-io** [comment]
At lease the `quay-data` and `pg-data` sub-folders should not be in `/etc`

**Comment by ibazulic** [comment]
@HammerMeetNail  IMHO it should be `/opt/quay-install`. According to the [Filesystem Hiearchy standard](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s13.html):

> 3.13.1. Purpose
> /opt is reserved for the installation of add-on application software packages.
> 
> A package to be installed in /opt must locate its static files in a separate /opt/<package> or /opt/<provider> directory tree, 
> where <package> is a name that describes the software package and <provider> is the provider's LANANA registered name.

**Comment by HammerMeetNail** [comment]
We've made some recent changes and the default install locations have changed. By default, the quay config will be installed to `$HOME/quay-install`. Systemd user services will also be installed to the `$HOME` directory. Postgres and Quay storage will now be stored in named volumes created by Podman. 

These defaults can be overwritten with command line args. Please note that at the moment both `--quayStorage` and `--pgStorage` will require the user to have `sudo` privileges, just like in earlier versions of mirror registry. 

```
# Quay config storage set via --quayRoot, Quay storage set via --quayStorage, Postgres storage set via --pgStorage
./mirror-registry uninstall -v --quayRoot /home/doconnor/quay-install --quayStorage /home/doconnor/quay-install/quay-storage --pgStorage /home/doconnor/quay-install/pg-data
```

This should resolve the issue. If you need anything else please let us know.
