### ISSUE TITLE
Crash on any commands after installation (upgrade, uninstall)

### ISSUE THREAD

**Issue by dovol** [quay/mirror-registry#64]
Hi everyone,

Can I get some help to resolve the following issue if I need to uninstall or upgrade my quay container?

[admin@PubRH mirror]$ sudo ./mirror-registry uninstall -v --targetHostname fqdn --targetUsername admin
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6d9092]

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).write(0xc0000120e0)
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:279 +0x52
github.com/sirupsen/logrus.(*Entry).log(0xc000012070, 0x1, 0xc00001c220, 0x1e)
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:251 +0x18b
github.com/sirupsen/logrus.(*Entry).Log(0xc000012070, 0xc000000001, 0xc0000ebc58, 0x1, 0x1)
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x86
github.com/sirupsen/logrus.(*Logger).Log(0x98afa0, 0x1, 0xc0000ebc58, 0x1, 0x1)
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/logger.go:198 +0x7e
github.com/sirupsen/logrus.(*Logger).Fatal(0x98afa0, 0xc0000ebc58, 0x1, 0x1)
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/logger.go:242 +0x51
github.com/quay/mirror-registry/cmd.getFQDN(0x98c140, 0xc0000fc100)
        /cli/cmd/utils.go:297 +0x92
github.com/quay/mirror-registry/cmd.init.0()
        /cli/cmd/install.go:81 +0x85

**Comment by HammerMeetNail** [comment]
Do you see the same behavior when not running as root? The current implementation does not support running with `sudo`.

**Comment by dovol** [comment]
yes, i have managed to uninstall it using root account. thank you so much!
