### ISSUE TITLE
online/offline assets are no longer published

### ISSUE THREAD

**Issue by jbpratt** [quay/mirror-registry#75]
Hi :smile_cat: , according to the README, there should be additional assets in the releases but there hasn't been since a May release. I guess the information in the README should be removed if this was intentional, as there is only one asset published [here](https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/mirror-registry/latest/), the offline asset.

**Comment by HammerMeetNail** [comment]
@jbpratt Good catch, you're absolutely right. We'll correct that with the next z-stream.

**Comment by HammerMeetNail** [comment]
This should be fixed now, see https://github.com/quay/mirror-registry/releases/tag/1.2.5
