### ISSUE TITLE
allow for disabling color in logs and ansible

### ISSUE THREAD

**Issue by jbpratt** [quay/mirror-registry#80]
When wrapping `mirror-registry` installation in additional automation (ansible), the output of a `command` execution of `mirror-registry` prints logs with ANSI escape codes. It would be awesome if there was a flag to disable any colored output.

https://docs.ansible.com/ansible/latest/reference_appendices/config.html#ansible-nocolor

https://github.com/quay/mirror-registry/blob/1f011e55135da2380a9169eb493a76d05cd7ba21/cmd/root.go#L44

![2022-08-16_07-25](https://user-images.githubusercontent.com/29494941/184879688-65ed6916-7fc7-4cf1-bbc7-11b581fcb346.png)

**Comment by HammerMeetNail** [comment]
Yeah, we can add a flag for that. If you have the bandwidth we love community contributions :)
