### ISSUE TITLE
Building should not be done as or require root

### ISSUE THREAD

**Issue by dmc5179** [quay/mirror-registry#91]
All commands in the Makefile start with "sudo". Building the code base should not require root access. And mistakes in the code or commands could seriously impact a system, i.e a misplaced rm -rf.

**Comment by dmc5179** [comment]
https://github.com/quay/mirror-registry/pull/92

**Comment by HammerMeetNail** [comment]
@dmc5179 Can you take a look at the PR? Needs a little adjusting.

**Comment by HammerMeetNail** [comment]
mirror registry can now be installed without root
